# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Desktop/FinalProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Desktop/FinalProject/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/FinalProject/build/CMakeFiles /home/pi/Desktop/FinalProject/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Desktop/FinalProject/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yolo11n

# Build rule for target.
yolo11n: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yolo11n
.PHONY : yolo11n

# fast build rule for target.
yolo11n/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/build
.PHONY : yolo11n/fast

bytetrack/src/BYTETracker.o: bytetrack/src/BYTETracker.cpp.o
.PHONY : bytetrack/src/BYTETracker.o

# target to build an object file
bytetrack/src/BYTETracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/BYTETracker.cpp.o
.PHONY : bytetrack/src/BYTETracker.cpp.o

bytetrack/src/BYTETracker.i: bytetrack/src/BYTETracker.cpp.i
.PHONY : bytetrack/src/BYTETracker.i

# target to preprocess a source file
bytetrack/src/BYTETracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/BYTETracker.cpp.i
.PHONY : bytetrack/src/BYTETracker.cpp.i

bytetrack/src/BYTETracker.s: bytetrack/src/BYTETracker.cpp.s
.PHONY : bytetrack/src/BYTETracker.s

# target to generate assembly for a file
bytetrack/src/BYTETracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/BYTETracker.cpp.s
.PHONY : bytetrack/src/BYTETracker.cpp.s

bytetrack/src/STrack.o: bytetrack/src/STrack.cpp.o
.PHONY : bytetrack/src/STrack.o

# target to build an object file
bytetrack/src/STrack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/STrack.cpp.o
.PHONY : bytetrack/src/STrack.cpp.o

bytetrack/src/STrack.i: bytetrack/src/STrack.cpp.i
.PHONY : bytetrack/src/STrack.i

# target to preprocess a source file
bytetrack/src/STrack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/STrack.cpp.i
.PHONY : bytetrack/src/STrack.cpp.i

bytetrack/src/STrack.s: bytetrack/src/STrack.cpp.s
.PHONY : bytetrack/src/STrack.s

# target to generate assembly for a file
bytetrack/src/STrack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/STrack.cpp.s
.PHONY : bytetrack/src/STrack.cpp.s

bytetrack/src/bytetrack.o: bytetrack/src/bytetrack.cpp.o
.PHONY : bytetrack/src/bytetrack.o

# target to build an object file
bytetrack/src/bytetrack.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/bytetrack.cpp.o
.PHONY : bytetrack/src/bytetrack.cpp.o

bytetrack/src/bytetrack.i: bytetrack/src/bytetrack.cpp.i
.PHONY : bytetrack/src/bytetrack.i

# target to preprocess a source file
bytetrack/src/bytetrack.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/bytetrack.cpp.i
.PHONY : bytetrack/src/bytetrack.cpp.i

bytetrack/src/bytetrack.s: bytetrack/src/bytetrack.cpp.s
.PHONY : bytetrack/src/bytetrack.s

# target to generate assembly for a file
bytetrack/src/bytetrack.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/bytetrack.cpp.s
.PHONY : bytetrack/src/bytetrack.cpp.s

bytetrack/src/kalmanFilter.o: bytetrack/src/kalmanFilter.cpp.o
.PHONY : bytetrack/src/kalmanFilter.o

# target to build an object file
bytetrack/src/kalmanFilter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/kalmanFilter.cpp.o
.PHONY : bytetrack/src/kalmanFilter.cpp.o

bytetrack/src/kalmanFilter.i: bytetrack/src/kalmanFilter.cpp.i
.PHONY : bytetrack/src/kalmanFilter.i

# target to preprocess a source file
bytetrack/src/kalmanFilter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/kalmanFilter.cpp.i
.PHONY : bytetrack/src/kalmanFilter.cpp.i

bytetrack/src/kalmanFilter.s: bytetrack/src/kalmanFilter.cpp.s
.PHONY : bytetrack/src/kalmanFilter.s

# target to generate assembly for a file
bytetrack/src/kalmanFilter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/kalmanFilter.cpp.s
.PHONY : bytetrack/src/kalmanFilter.cpp.s

bytetrack/src/lapjv.o: bytetrack/src/lapjv.cpp.o
.PHONY : bytetrack/src/lapjv.o

# target to build an object file
bytetrack/src/lapjv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/lapjv.cpp.o
.PHONY : bytetrack/src/lapjv.cpp.o

bytetrack/src/lapjv.i: bytetrack/src/lapjv.cpp.i
.PHONY : bytetrack/src/lapjv.i

# target to preprocess a source file
bytetrack/src/lapjv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/lapjv.cpp.i
.PHONY : bytetrack/src/lapjv.cpp.i

bytetrack/src/lapjv.s: bytetrack/src/lapjv.cpp.s
.PHONY : bytetrack/src/lapjv.s

# target to generate assembly for a file
bytetrack/src/lapjv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/lapjv.cpp.s
.PHONY : bytetrack/src/lapjv.cpp.s

bytetrack/src/utils.o: bytetrack/src/utils.cpp.o
.PHONY : bytetrack/src/utils.o

# target to build an object file
bytetrack/src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/utils.cpp.o
.PHONY : bytetrack/src/utils.cpp.o

bytetrack/src/utils.i: bytetrack/src/utils.cpp.i
.PHONY : bytetrack/src/utils.i

# target to preprocess a source file
bytetrack/src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/utils.cpp.i
.PHONY : bytetrack/src/utils.cpp.i

bytetrack/src/utils.s: bytetrack/src/utils.cpp.s
.PHONY : bytetrack/src/utils.s

# target to generate assembly for a file
bytetrack/src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/utils.cpp.s
.PHONY : bytetrack/src/utils.cpp.s

bytetrack/src/yolo11n.o: bytetrack/src/yolo11n.cpp.o
.PHONY : bytetrack/src/yolo11n.o

# target to build an object file
bytetrack/src/yolo11n.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/yolo11n.cpp.o
.PHONY : bytetrack/src/yolo11n.cpp.o

bytetrack/src/yolo11n.i: bytetrack/src/yolo11n.cpp.i
.PHONY : bytetrack/src/yolo11n.i

# target to preprocess a source file
bytetrack/src/yolo11n.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/yolo11n.cpp.i
.PHONY : bytetrack/src/yolo11n.cpp.i

bytetrack/src/yolo11n.s: bytetrack/src/yolo11n.cpp.s
.PHONY : bytetrack/src/yolo11n.s

# target to generate assembly for a file
bytetrack/src/yolo11n.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/bytetrack/src/yolo11n.cpp.s
.PHONY : bytetrack/src/yolo11n.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yolo11n.dir/build.make CMakeFiles/yolo11n.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... yolo11n"
	@echo "... bytetrack/src/BYTETracker.o"
	@echo "... bytetrack/src/BYTETracker.i"
	@echo "... bytetrack/src/BYTETracker.s"
	@echo "... bytetrack/src/STrack.o"
	@echo "... bytetrack/src/STrack.i"
	@echo "... bytetrack/src/STrack.s"
	@echo "... bytetrack/src/bytetrack.o"
	@echo "... bytetrack/src/bytetrack.i"
	@echo "... bytetrack/src/bytetrack.s"
	@echo "... bytetrack/src/kalmanFilter.o"
	@echo "... bytetrack/src/kalmanFilter.i"
	@echo "... bytetrack/src/kalmanFilter.s"
	@echo "... bytetrack/src/lapjv.o"
	@echo "... bytetrack/src/lapjv.i"
	@echo "... bytetrack/src/lapjv.s"
	@echo "... bytetrack/src/utils.o"
	@echo "... bytetrack/src/utils.i"
	@echo "... bytetrack/src/utils.s"
	@echo "... bytetrack/src/yolo11n.o"
	@echo "... bytetrack/src/yolo11n.i"
	@echo "... bytetrack/src/yolo11n.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

